name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false       # <-- avoid shallow/broken submodule fetches
          fetch-depth: 0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Show Foundry config + remappings
        run: |
          echo "== foundry.toml =="
          cat foundry.toml || true
          echo "== forge config (effective) =="
          forge config
          echo "== forge remappings (effective) =="
          forge remappings || true
          echo "== lib tree =="
          ls -la lib || true    

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
